name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        SECRET_KEY: ${{secrets.SECRET_KEY}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build . 
    - name: Docker Tag
      run: Docker Tag healthcare-demo ${{secrets.DOCKER_USERNAME}}/healthcare-demo
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/healthcare-demo
  